# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Duration-ja
version:      0.02
version_from: lib/Time/Duration/ja.pm
installdirs:  site
requires:
    Encode:                        0
    encoding:                      0
    Test::More:                    0.32
    Time::Duration:                1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.27
